name: Build

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.200
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Publish iBestRead.Result to NuGet
      uses: brandedoutcast/publish-nuget@v2.5.4
      with:
          PROJECT_FILE_PATH: src/iBestRead.Result/iBestRead.Result.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}

    - name: Publish iBestRead.Result.AspNetCoreExtensions to NuGet
      uses: brandedoutcast/publish-nuget@v2.5.4
      with:
          PROJECT_FILE_PATH: src/iBestRead.Result.AspNetCoreExtensions/iBestRead.Result.AspNetCoreExtensions.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}

    - name: Publish iBestRead.Result.FluentValidationExtensions to NuGet
      uses: brandedoutcast/publish-nuget@v2.5.4
      with:
          PROJECT_FILE_PATH: src/iBestRead.Result.FluentValidationExtensions/iBestRead.Result.FluentValidationExtensions.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}